### ISSUE TITLE
Update envtest-run's controller-runtime version to be in sync with source code version

### ISSUE THREAD

**Issue by chr12c** [sky-uk/kfp-operator#644]
## Is your feature request related to a problem? Please describe
The `envtest-run` is still using `0.8.3` - which is far behind the actual version of the controller-runtime being used in source code.

## Describe the solution you would like
Update this value. Make it automated

## Describe alternative solutions you have considered

A clear and concise description of any alternative solutions or features you've considered, if any.

## Additional context

in setup-env.sh the variable ENVTEST_K8S_VERSION had to be hacked from 1.19.2 to 1.29.0 because that's the minimum version that support apple silicone

**Comment by chr12c** [comment]
as of [0.9.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.9.0), there is no more `setup-envtest.sh`.
The particular change was introduced in https://github.com/kubernetes-sigs/controller-runtime/pull/1488

**Comment by chr12c** [comment]
The [solution is to use the envtest binaries manager](https://github.com/kubernetes-sigs/controller-runtime/tree/main/tools/setup-envtest), however that tool requires at least golang 1.23.x
Since this repo is still on 1.22.x, that means this issue is blocked until the upgrade is made.

**Comment by chr12c** [comment]
no longer blocked by golang version because it was upgraded to 1.24.x in https://github.com/sky-uk/kfp-operator/pull/743.
However it is now at least partially blocked by some validation webhooks using the deprecated `Validator` interface. envtest requires the `CustomValidator`:

```
make decoupled-test
eval "$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest use -p env 1.29.x)"
go test ./controllers/pipelines/... -tags=decoupled -coverprofile cover.out
# sigs.k8s.io/controller-runtime/pkg/internal/controller
../../.asdf/installs/golang/1.24.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.6/pkg/internal/controller/controller.go:103:9: not enough arguments in call to fn
        have (interface{})
        want (context.Context, interface{})
# sigs.k8s.io/controller-runtime/pkg/webhook/admission
../../.asdf/installs/golang/1.24.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.6/pkg/webhook/admission/webhook.go:158:9: not enough arguments in call to fn
        have (interface{})
        want (context.Context, interface{})
```

issue to upgrade interface: https://github.com/sky-uk/kfp-operator/issues/785

**Comment by chr12c** [comment]
later versions of controller runtime (~0.22.x, have not checked the exact version but does not matter), it's possible to not bother with envtest binaries manager and directly download the binaries by specifying it in the Environment
